### ISSUE TITLE
Custom Gcode Not Visible in Print Visualizer

### ISSUE THREAD

**Issue by peterhuson** [makerfleet/bug_reporting#5]
### Browser 

Chrome 77

### Operating System 

MacOs 10.12.6

## Expected Behavior
The print visualizer should generate a visualization of the custom Gcode. 

## Current Behavior
A blank build plate is shown in the visualizer: 
![IMG_0383](https://user-images.githubusercontent.com/9157695/67321452-84888500-f4dd-11e9-8095-636b3a5bc307.jpeg)

## Steps to Reproduce
1. Upload custom gcode. Seen below: 
2. https://cloud.makerfleet.com/print?printId=5da5e2187aa33e000d31f497

**Comment by HakuG** [comment]
Hmm, When you upload something, it won't show the gcode immediately:

You have to click "Print Visualizer on" to turn it on. 

Is that the problem?

**Comment by peterhuson** [comment]
It won't show up even when this switch is turned on. 
![IMG_0384](https://user-images.githubusercontent.com/9157695/67321690-da5d2d00-f4dd-11e9-9c81-00b726e493ff.jpeg)

**Comment by HakuG** [comment]
Hmm, that's really weird. Can you send the gcode file to team@makerfleet.com? We'll take a look at it.

**Comment by peterhuson** [comment]
Custom gcode seems to work for other prints, it could have to do with the gcode in question having some non-planar print commands. 

Other gcode being visualized properly: 
![IMG_0385](https://user-images.githubusercontent.com/9157695/67322221-b51cee80-f4de-11e9-9ff9-9d107da2c801.jpeg)

**Comment by HakuG** [comment]
Yeah, it's because it's non planar. It has a Z value at every Gcode command, which isn't usually the case. On the visualizer, we assume that each time we see a Z, it's a part of a new layer and not extruding at the same time. The visualizer may not show it, but the gcode file itself should work on the printer, as long as the firmware supports it.

Closing this for now. It's something we'll work on in the future, but this seems like a corner case to keep in mind in the future.
